### ISSUE TITLE
add PARSE_DASHBOARD_CONFIG

### ISSUE THREAD

**Issue by johnnyzen** [bitnami/bitnami-docker-parse-dashboard#33]
Hi there

I would like to specify my own dashboard config.

Please can you add config option PARSE_DASHBOARD_CONFIG or help me to understand how I can do this without the docker config option.

Many thanks

Johnny

**Comment by juan131** [comment]
Hi @johnnyzen 

Did you check the section below?
https://github.com/bitnami/bitnami-docker-parse-dashboard#environment-variables

Are you looking for a solution that allows you to inject the whole configuration file (via volume)?
