### ISSUE TITLE
No option to access parse via https from dashboard

### ISSUE THREAD

**Issue by broken-bytes** [bitnami/bitnami-docker-parse-dashboard#35]
**Description**

No option to access parse via https from dashboard

**Steps to reproduce the issue:**

1. Download the docker-compose.yml
2. Setup your instance
3. Proxy it with nginx/apache and access the dashboard over https
4. The dashboard won't be able to access the server anymore as calls are made via http which is forbidden when connecting via https

**Output**
dashboard.bundle.js:45341 Mixed Content: The page at 'https://***apps' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://***:1337/parse/serverInfo'. This request has been blocked; the content must be served over HTTPS.

**Comment by javsalgar** [comment]
I think this could be related with https://github.com/bitnami/bitnami-docker-parse-dashboard/issues/34

**Comment by broken-bytes** [comment]
No, I still get this error even though I fixed #34

**Comment by juan131** [comment]
@broken-bytes I just answered at #34
