### ISSUE TITLE
Blank page after login

### ISSUE THREAD

**Issue by Blacktoviche** [bitnami/bitnami-docker-parse-dashboard#38]
Everything running fine 
but after login to dashboard I got the waiting loop it redirect me to http://ip//apps/MyDashboard/browser then a blank page 

OS: Ubuntu on virtual machine 

Here is docker output 

parse_1            | 
parse_1            | [20] parse-server running on http://127.0.0.1:1337/parse
parse_1            | 
parse_1            | WARNING, Unable to connect to 'http://127.0.0.1:1337/parse'. Cloud code and push notifications may be unavailable!
parse_1            | 
mongodb_1          | 2019-04-30T08:37:47.017+0000 I NETWORK  [listener] connection accepted from 172.20.0.3:35230 #1 (1 connection now open)
mongodb_1          | 2019-04-30T08:37:47.021+0000 I NETWORK  [conn1] received client metadata from 172.20.0.3:35230 conn1: { driver: { name: "nodejs", version: "3.2.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-48-generic" }, platform: "Node.js v8.16.0, LE, mongodb-core: 3.2.3" }
parse_1            | Warning: no saslprep library specified. Passwords will not be sanitized
mongodb_1          | 2019-04-30T08:37:47.045+0000 I ACCESS   [conn1] Successfully authenticated as principal bn_parse on bitnami_parse
mongodb_1          | 2019-04-30T08:37:47.061+0000 I NETWORK  [listener] connection accepted from 172.20.0.3:35232 #2 (2 connections now open)
mongodb_1          | 2019-04-30T08:37:47.063+0000 I NETWORK  [conn2] received client metadata from 172.20.0.3:35232 conn2: { driver: { name: "nodejs", version: "3.2.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-48-generic" }, platform: "Node.js v8.16.0, LE, mongodb-core: 3.2.3" }
parse_1            | Warning: no saslprep library specified. Passwords will not be sanitized
mongodb_1          | 2019-04-30T08:37:47.066+0000 I ACCESS   [conn2] Successfully authenticated as principal bn_parse on bitnami_parse
mongodb_1          | 2019-04-30T08:37:47.077+0000 I NETWORK  [listener] connection accepted from 172.20.0.3:35234 #3 (3 connections now open)
mongodb_1          | 2019-04-30T08:37:47.078+0000 I NETWORK  [conn3] received client metadata from 172.20.0.3:35234 conn3: { driver: { name: "nodejs", version: "3.2.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-48-generic" }, platform: "Node.js v8.16.0, LE, mongodb-core: 3.2.3" }
parse_1            | Warning: no saslprep library specified. Passwords will not be sanitized
mongodb_1          | 2019-04-30T08:37:47.081+0000 I ACCESS   [conn3] Successfully authenticated as principal bn_parse on bitnami_parse
mongodb_1          | 2019-04-30T08:37:47.085+0000 I NETWORK  [listener] connection accepted from 172.20.0.3:35236 #4 (4 connections now open)
mongodb_1          | 2019-04-30T08:37:47.087+0000 I NETWORK  [conn4] received client metadata from 172.20.0.3:35236 conn4: { driver: { name: "nodejs", version: "3.2.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-48-generic" }, platform: "Node.js v8.16.0, LE, mongodb-core: 3.2.3" }
parse_1            | Warning: no saslprep library specified. Passwords will not be sanitized
mongodb_1          | 2019-04-30T08:37:47.090+0000 I ACCESS   [conn4] Successfully authenticated as principal bn_parse on bitnami_pars`
`

**Comment by alemorcuq** [comment]
Hi, @Blacktoviche.

I would like more information in order to be able to reproduce the issue. Can you give me some steps to follow? (e. g. if you are using `docker-compose` then it would be good to have your `docker-compose.yml` file —without any sensible data).

Apart from that, I think this issue may be related to the `PARSE_HOST` environment variable. Are you setting it to your ip in your `parse-dashboard` container?

Regards,
Alejandro

**Comment by Blacktoviche** [comment]
Hi aljandro
I used this from repository 
 `curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-parse-dashboard/master/docker-compose.yml > docker-compose.yml
docker-compose up -d`

I didn't set any environment variable.
Shouldn't it install parse server too? 
it installed parse server and mongodb

**Comment by alemorcuq** [comment]
Hi, @Blacktoviche.

Try setting the `PARSE_HOST` environment variable in your `parse-dashboard` container. Like this:

```docker-compose
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:1'
    ports:
      - '80:4040'
    environment:
      - 'PARSE_HOST=YOUR_IP'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```

Replace `YOUR_IP` with the IP you use to access `parse-dashboard` through your browser. Then bring down your containers and bring them up again:

```bash
$ docker-compose down -v
$ docker-compose up -d
```

Regards,
Alejandro

**Comment by Blacktoviche** [comment]
Thanks @alemorcuq  after setting PARSE_HOST  it works fine
There are some errors in the dashboard log
RESTController.js:205 POST http://192.168.1.117:1337/parse/schemas 500 (Internal Server Error)
RESTController.js:205 POST http://192.168.1.117:1337/parse/schemas 500 (Internal Server Error)
RESTController.js:205 POST http://192.168.1.117:1337/parse/schemas 500 (Internal Server Error)
RESTController.js:205 POST http://192.168.1.117:1337/parse/schemas 500 (Internal Server Error)`
`
I will check it

**Comment by juan131** [comment]
> Thanks @alemorcuq after setting PARSE_HOST it works fine

That's great @Blacktoviche ! I'm glad you could properly configure Parse Dashboard.

> There are some errors in the dashboard log

What actions did you perform through the Dashboard (or directly addressing the Parse API) before you saw those logs? 
Did you create new classes or webhooks?

**Comment by Blacktoviche** [comment]
I did nothing the error showed after I logged in the first time, I shutdown the server 
Next login the error disappeared.

But I found that there is no menu to add  apps
![parse_1](https://user-images.githubusercontent.com/16650583/57048799-18d80480-6c7e-11e9-81e5-f4b1e4321732.png)
![parse_2](https://user-images.githubusercontent.com/16650583/57048805-21c8d600-6c7e-11e9-96a3-3c58564b26ba.png)

**Comment by alemorcuq** [comment]
Hi, @Blacktoviche.

I am no Parse Dashboard expert, but I think that's not a feature they offer. In their documentation they state that [in order to manage multiple apps you have to add them to your config file](https://github.com/parse-community/parse-dashboard#managing-multiple-apps).

Regards,
Alejandro

**Comment by Blacktoviche** [comment]
Yeah I read about editing configs to add apps 
Thanks @alemorcuq  so much
