### ISSUE TITLE
Support for GraphQL playground

### ISSUE THREAD

**Issue by tk2232** [bitnami/bitnami-docker-parse-dashboard#40]
**Description**

Is it possible to enable graphql playground with this image?

I've tried to add PARSE_DASHBOARD_GRAPHQL_URL to the environments but there is no entry in the config.json after deploy.

**Comment by andresbono** [comment]
Hi @tk2232, I'm afraid that environment variable is not supported. You can see the supported ones here: https://github.com/bitnami/bitnami-docker-parse-dashboard/blob/master/2/debian-10/rootfs/parse-dashboard-inputs.json and the documentation about them here: https://github.com/bitnami/bitnami-docker-parse-dashboard#environment-variables.

You might want to modify the configuration file manually. It will be persisted in a volume.
