### ISSUE TITLE
Parse Dashboard's infinite loading and not showing the actual dashboard.

### ISSUE THREAD

**Issue by nuriyevn** [bitnami/bitnami-docker-parse-dashboard#43]
**Description**

I have compsed docker up parse and parse dashboard so I should have
http://194.0.52.235:4040/
dashboard working.
but now I experience an infinite load loop 
it redirected to http://194.0.52.235:4040/apps/MyDashboard/browser
and red.blue.green circles are rotating  
![image](https://user-images.githubusercontent.com/6706940/135972634-d57284fc-06b8-484d-88a8-903ee5c8b5f5.png)
some time maybe a minute and then I have just blank creamy background without circles already.

**Steps to reproduce the issue:**

1. Enter web-site
2. Wait a few minutes 1-2-3 (I don't know what exact timeout)
3. Enjoy or blame blank screen

**Describe the results you received:**

**Describe the results you expected:**

i expect to see dashboard with the list of objects in other word and fully functioned dashboard

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

Docker version 18.09.7, build 2d0083d

- Output of `docker info`:

Containers: 17
 Running: 9
 Paused: 0
 Stopped: 8
Images: 290
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-142-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 15.63GiB
Name: nusik-ProLiant-DL385-G7
ID: YX45:ZKFS:Y6GY:XKL5:3ABI:AWHZ:YFQ6:TPVW:XDGH:GQOJ:5SLS:2ZDU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: nuriyevn
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

- Output of `docker-compose version` (if applicable):

docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Physical server.

Some time before it was working. There are some data there.
I can get those data by this request

curl -X GET \
  -H "X-Parse-Application-Id: MY_APP_ID" \
  -H "X-Parse-Master-Key: MY_APP_MASTER_KEY" \
  http://localhost:1337/parse/classes/_User

from the server

**Comment by alemorcuq** [comment]
Hi, @nuriyevn.

I think you are missing the `PARSE_HOST` environment variable. Can you share your `docker-compose.yml` file?

**Comment by nuriyevn** [comment]
Here is my docker-compose.yml

version: '2'
services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.2
    restart: always
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: docker.io/bitnami/parse:4
    restart: always
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: docker.io/bitnami/parse-dashboard:2
    restart: always
    ports:
      - '4040:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local

**Comment by nuriyevn** [comment]
it is in the following network

docker network inspect test_docker_default
[
    {
        "Name": "test_docker_default",
        "Id": "51dbfb4d81362bef76ecd02ec1464f14b72bb1e4ef8b29842d6f136d6821d589",
        "Created": "2021-06-05T01:54:48.165963597+03:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.23.0.0/16",
                    "Gateway": "172.23.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "2bad14d9d954a268958fa2127c04adfadec5af744fe1d709aa0f09b8ea37fc0b": {
                "Name": "test_docker_mongodb_1",
                "EndpointID": "4f459f197b97a69b76b19953a87796f5479a328881d7e57409fe1346d71247ec",
                "MacAddress": "02:42:ac:17:00:02",
                "IPv4Address": "172.23.0.2/16",
                "IPv6Address": ""
            },
            "491c2216028be0fbb458ccbb8cdeb2a14988f83a54b6b6e10bdf1e8e24cfc25d": {
                "Name": "test_docker_parse_1",
                "EndpointID": "00e2cdc65e3fcf7edd5608d7b0a7e44ded8fb4822fe08f7a72e81422fd72539b",
                "MacAddress": "02:42:ac:17:00:03",
                "IPv4Address": "172.23.0.3/16",
                "IPv6Address": ""
            },
            "7aaf75690b7c1cd28321ed0d144faca971e3b04644ad09a29e1f27e68eb465c8": {
                "Name": "test_docker_parse-dashboard_1",
                "EndpointID": "a35e901ebe127e4a4d06f2256af980fff9a52ae8f6509375dcf4551692e369c0",
                "MacAddress": "02:42:ac:17:00:04",
                "IPv4Address": "172.23.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]


so the 
/opt/bitnami/parse-dashboard/config.json is following

{
  "apps": [
    {
      "serverURL": "http://172.23.0.3:1337/parse",
      "appId": "<myid>",
      "masterKey": "<mykey>",
      "appName": "MyDashboard"
    }
  ],
  "users": [
    {
      "user": "user",
      "pass": "<mypass>"
    }
  ]
}

**Comment by nuriyevn** [comment]
I have change the addres of server from 172.23.0.3 - docker ip to global 194.0.52.235
Now, the problem is with SSL protocol error.

This will be in another issue.
