### ISSUE TITLE
parse-dashboard  doesn't work with multiple app (even with one app)

### ISSUE THREAD

**Issue by nuriyevn** [bitnami/bitnami-docker-parse-dashboard#44]
**Description**

parse-dashboard 20:33:07.11 WARN  ==> Parse Dashboard config.json detected in persistence. Persisting configuration files is deprecated
parse-dashboard 20:33:07.15 INFO  ==> Trying to connect to the Parse server "http://172.26.0.9:1337/parse"
parse-dashboard 20:34:07.89 ERROR ==> Could not connect to Parse

though

curl -X GET   -H "X-Parse-Application-Id: mykeyId"   -H "X-Parse-Master-Key: mymasterKey"   http://172.26.0.9:1337/parse/classes/_User

works through console.

**Steps to reproduce the issue:**

0. Modify file  /bitnami/parse-dashoard/config.json
{ 
  "apps": [
    {
      "serverURL": "http://172.26.0.9:1337/parse",
      "appId": "mykeyId",
      "masterKey": "mymasterKey",
      "appName": "MyApp"
    }
  ],
  "users": [
    {
      "user": "user",
      "pass": "bitnami"
    }
  ]
}
1. start parse-dashboard docker container
2.  wait 1 minute for error
3. Get "Could not connect to Parse" error

**Describe the results you received:**

I get error 

parse-dashboard 20:33:07.11 WARN  ==> Parse Dashboard config.json detected in persistence. Persisting configuration files is deprecated
parse-dashboard 20:33:07.15 INFO  ==> Trying to connect to the Parse server "http://172.26.0.9:1337/parse"
parse-dashboard 20:34:07.89 ERROR ==> Could not connect to Parse

while outputting
docker logs container_name

**Describe the results you expected:**

I expect to see working  parse dashboard

**Version**

- Output of `docker version`:

Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Wed Oct 14 19:42:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Wed Oct 14 17:25:58 2020
  OS/Arch:          linux/amd64
  Experimental:     false

- Output of `docker info`:
Containers: 29
 Running: 16
 Paused: 0
 Stopped: 13
Images: 294
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-142-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 15.63GiB
Name: nusik-ProLiant-DL385-G7
ID: YX45:ZKFS:Y6GY:XKL5:3ABI:AWHZ:YFQ6:TPVW:XDGH:GQOJ:5SLS:2ZDU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: nuriyevn
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

- Output of `docker-compose version` (if applicable):

docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

It does not work even when the app count is one

**Comment by nuriyevn** [comment]
curl 192.168.1.119....   lan address
curl 172.26.0.9... docker lan address
everything works from command line

like this
curl -X GET   -H "X-Parse-Application-Id: myappId"   -H "X-Parse-Master-Key: mymasterKey"   http://172.26.0.9:1337/parse/classes/_User

**Comment by juan131** [comment]
Hi @nuriyevn 

Please note most of these env. variable that we expose to configure the container are "first run only". This means that once the apps is launched and configured for the 1s time, the configuration is persisted and reused on container restarts (ignoring the values you add in the env. variables).

It could be possible that's your problem and the difference between the behaviour you're experiencing using DockerCompose vs `docker run..`: you're persisting the configuration using DockerCompose (check the "volumes" section) while you're not doing the same with `docker run...`. Please try running the command below before relaunching your containers:

```console
docker-compose down -v
```

That will ensure that both containers **and volumes** are deleted, guaranteeing a "clean" environment when launching the containers again.
