### ISSUE TITLE
rest api key for docker-compose.yaml

### ISSUE THREAD

**Issue by 4cecoder** [bitnami/bitnami-docker-parse-dashboard#48]
**Description**
There is no available configuration option to specify REST_API_KEY in the docker-compose file ENVIRONMENT variables

**Comment by carrodher** [comment]
There is not any environment variable in the container for `REST_API_KEY`, in order to use it in the docker-compose, it should be added previously to the container.

Would you like to contribute by creating a PR? The team will be happy to review it and provide feedback

**Comment by 4cecoder** [comment]
Hello @carrodher , 

ok, i'll give you guys a little pull in order to ... extend functionality... for parse params of course...
Thanks in advance to bit TEAM, would appreciate the review and feedback!
